const translations = {
  en: {
    home: "Home",
    about: "About",
    contact: "Contact Us",
    title: "Your destination for the best music",
    description: "Discover artists, releases, and everything you need to vibe to the rhythm of music.",
    artists: "Artists",
    artistTitle: "Our Artists",
    contactTitle: "Contact Us",
    contactDescription: "If you have any questions, suggestions, or just want to get in touch with us, feel free to send us a message. We are here to help and listen to your feedback.",
    aboutFiarreMusic: "Acerca de Fiarre Music",
    info: "Our mission and vision is defined by providing the opportunity to venture into the art and music industry in a healthy, pleasant, and achievable way for all those who have already decided to take this path. Communication, respect, trust, talent, perseverance, and dedication are key pieces in the formula for musical success. If the thought of being an artist crosses your mind, it crosses your heart; allow the <b>Fiarre Music</b> family to unleash your passion.",
    btnartists: "Meet our artists",
    btnacerca: "Learn about us",
    btncontactanos: "Contact Us",
  },
  es: {
    home: "Inicio",
    about: "Acerca de",
    contact: "Contáctanos",
    title: "Tu destino para la mejor música",
    description: "Descubre artistas, lanzamientos y todo lo que necesitas para vibrar al ritmo de la música.",
    artists: "Artistas",
    artistTitle: "Nuestros Artistas",
    contactTitle: "Contactanos",
    contactDescription: "Si tienes alguna pregunta, sugerencia o simplemente quieres ponerte en contacto con nosotros, no dudes en enviarnos un mensaje. Estamos aquí para ayudarte y escuchar tus comentarios.",
    aboutFiarreMusic: "About Fiarre Music",
    info: "Nuestra mision y vision se define en brindar la oportunidad de incursionar en el arte y la industria músical de una forma sana, grata y alcanzable a todos aquellos que ya se propusieron tomar este camino. Comunicación, respeto, confianza, talento, perseverancia y dedicación son piezas claves en la fórmula del éxito musical. Si paso por tu mente ser artista, paso por tu corazón, permite que la familia de <b>Fiarre Music</b> le de rienda suelta tu pasión.",
    btnartists: "Conoce a nuestros artistas",
    btnacerca: "Conoce sobre nosotros",
    btncontactanos: "Conoce a nuestros artistas",
  }
};
